language: python
python:
  - "2.7"
  - "3.3"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.2
env:
  - DJANGO=1.4.2
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=tests,migrations --ignore=E124,E128 rules_light"
script:
  - python setup.py test
notifications:
  irc: "irc.freenode.org#neoskills"
